package com.example.demo.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * A Sale is created when a CONFIRMED booking is fully paid and the vehicle handed over.
 * It carries the unique invoice number and payment breakdown.
 *
 * Lifecycle of a vehicle:
 *   Stock AVAILABLE → (Booking) → Stock BOOKED → (Sale) → Stock SOLD
 */
@Entity
@Table(name = "sales")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(callSuper = true)
public class Sale extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "sale_id")
    private Long saleId;

    /** The booking that originated this sale. */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "booking_id", nullable = false, unique = true)
    private Booking booking;

    /** Denormalised for fast lookup without joining through booking. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vin", nullable = false)
    private VehicleStock vehicleStock;

    /**
     * Human-readable invoice number.
     * Format: INV-{YYYY}-{zero-padded 6-digit sequence}
     * Example: INV-2025-000042
     * Generated by InvoiceSequenceService at sale creation time.
     */
    @Column(name = "invoice_number", unique = true, nullable = false)
    private String invoiceNumber;

    @Column(name = "sale_date", nullable = false)
    private LocalDate saleDate;

    /** Final agreed sale price (ex-showroom ± discounts/additions). */
    @Column(name = "sale_price", precision = 12, scale = 2, nullable = false)
    private BigDecimal salePrice;

    /** CASH | LOAN | EXCHANGE | MIXED */
    @Column(name = "payment_mode")
    private String paymentMode;

    /** Finance/loan amount (0 for full cash). */
    @Column(name = "loan_amount", precision = 12, scale = 2)
    private BigDecimal loanAmount;

    /** Name of the financing bank, if any. */
    @Column(name = "finance_bank")
    private String financeBank;

    /** Exchange vehicle description, if any. */
    @Column(name = "exchange_vehicle")
    private String exchangeVehicle;

    /** Value offered for the exchange vehicle. */
    @Column(name = "exchange_value", precision = 12, scale = 2)
    private BigDecimal exchangeValue;

    /** Free-text remarks printed on the invoice. */
    @Column(name = "remarks")
    private String remarks;

    /**
     * Payment status.
     * PENDING → PAID (full payment received)
     */
    @Builder.Default
    @Column(name = "payment_status")
    private String paymentStatus = "PENDING";
}
